### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by prashantbarca** [faizaanceg/u-r-l-s#1]
I entered links like 

jkjl or something as the shortened route. 
youp*** for the url (Without the http/https/www) . 

Guess what happened? :P

**Comment by faizaanceg** [comment]
Yeah..have to implement client side validation to support only fully-qualified URLs.

**Comment by arjunmayilvaganan** [comment]
@faizaanceg, Why did you close this issue? :tongue:

**Comment by faizaanceg** [comment]
It's fixed thats why :P

**Comment by arjunmayilvaganan** [comment]
@faizaanceg, You thought, I'd comment without even checking it first? 😦
Or you didn't even bother to check once again before responding? 🙄

![screen shot 2015-11-04 at 7 10 38 pm](https://cloud.githubusercontent.com/assets/6371303/10939558/6925d4d2-8328-11e5-8c8e-2171ea38fdc9.png)


![screen shot 2015-11-04 at 7 06 34 pm](https://cloud.githubusercontent.com/assets/6371303/10939575/85596bd2-8328-11e5-9dce-ee7e31eb30c9.png)

**Comment by faizaanceg** [comment]
The client side validation doesn't work in some browsers. Will add server-side validation too

**Comment by arjunmayilvaganan** [comment]
@faizaanceg, Also include validation to check if TLD part present.

**Comment by faizaanceg** [comment]
:+1:  Will do

**Comment by faizaanceg** [comment]
Rewriting project. So closing this
